exclude: "^{{cookiecutter\\.project_name}}/"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.0
    hooks:
      - id: prettier
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.33.1
    hooks:
      - id: check-github-workflows
        args: [ "--verbose" ]
