# .pre-commit-config.yaml
# See https://pre-commit.com/
default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        args: ["--max-size=1000000"]
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.11
    hooks:
      - id: ruff-format
        args: [--config=.ruff.toml]

      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --config=.ruff.toml]
