# .github/workflows/docs-build-python.yml
# See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: Build Python Documentation

on:
  pull_request:
    paths:
      - 'docs/**'
      - 'src/**/*.py'
      - 'noxfile.py'
      - 'pyproject.toml'
      - '.github/workflows/docs-build-python.yml'
      - '.ruff.toml' # Affects docstrings via linting
      - 'pyrightconfig.json' # Affects type hints in docs
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'src/**/*.py'
      - 'noxfile.py'
      - 'pyproject.toml'
      - '.github/workflows/docs-build-python.yml'

  workflow_dispatch:

jobs:
  build-python-docs:
    name: Run Python Documentation Build Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Build documentation
        run: uvx nox -s docs-build

      - name: Upload documentation (HTML) Artifact
        uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: docs/_build/html/
          retention-days: 5
